name: 'Addon-HyperHDR'

# Controls when the action will run
on: [ workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs Node JS
      - uses: actions/setup-node@v1

      # Sync version to source
      - run: ./.github/scripts/update-hyperhdr-version.sh

      - shell: bash
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: ./.github/scripts/build.sh amd64 &&
             ./.github/scripts/build.sh armhf && 
             ./.github/scripts/build.sh aarch64

      - uses: test-room-7/action-update-file@v1
        if: ${{ env.VERSION != env.RELEASE }}
        with:
          file-path: addon-hyperhdr/config.json
          commit-msg: Update version
          github-token: ${{ secrets.GH_TOKEN }}

      - uses: actions/create-release@v1
        if: ${{ env.VERSION != env.RELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE }}
          release_name: ${{ env.RELEASE }}
          draft: false
          prerelease: false
